---
title: "Data Visualization"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
theme_set(theme_bw())
```

## Load the Dataset
```{r}
dat <- read.csv("../dataset/clean_diabetic_data.csv")
```

## Composition Graphs 
```{r}
ggplot(data=dat, aes(x=factor(race, labels = c("Caucasian", "African American", "Other")), 
                              fill=factor(readmitted, 
                                          labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) +
  geom_bar(position=position_dodge(), color = "black") +
  labs(title="Categorywise Bar Chart of Race", x="Race", y="Count", fill="Readmission Status") 
```

```{r}
ggplot(data=dat, aes(x=factor(gender, labels = c("Female", "Male")), 
                              fill=factor(readmitted, 
                                          labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) +
  geom_bar(position=position_dodge(), color = "black") +
  labs(title="Categorywise Bar Chart of Gender", x="Gender", y="Count", fill="Readmission Status") 
```

```{r}
ggplot(data=dat, aes(x=factor(max_glu_serum, labels = c("No Measurement", "Normal Reading", ">200", ">300")), 
                              fill=factor(readmitted, 
                                          labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) +
  geom_bar(position=position_dodge(), color = "black") +
  labs(title="Categorywise Bar Chart of Glucose Serum", x="Glucose Serum", y="Count", fill="Readmission Status") 
```

```{r}
ggplot(data=dat, aes(x=factor(A1Cresult, labels = c("No Measurement", "Normal Reading", ">7")), 
                              fill=factor(readmitted, 
                                          labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) +
  geom_bar(position=position_dodge(), color = "black") +
  labs(title="Categorywise Bar Chart of A1C Test Result", x="A1C", y="Count", fill="Readmission Status") 
```

```{r}
ggplot(data=dat, aes(x=factor(insulin, labels = c("No Insulin", "Decrease in Insulin", "Steady Insulin", "Increase in Insulin")), 
                              fill=factor(readmitted, 
                                          labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) +
  geom_bar(position=position_dodge(), color = "black") +
  labs(title="Categorywise Bar Chart of Insulin Change", x="Insulin Change", y="Count", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(change, labels = c("No Change", "Change in Medication")), 
                              fill=factor(readmitted, 
                                          labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) +
  geom_bar(position=position_dodge(), color = "black") +
  labs(title="Categorywise Bar Chart of Medication Change", x="Medication Change", y="Count", fill="Readmission Status")
```

## Distribution Graphs

```{r}
ggplot(data=dat, aes(x=time_in_hospital, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="Time in Hospital", y="Density", 
       title="Distribution of Time in Hospital Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=time_in_hospital)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="Time in Hospital", x="Readmission Status", 
       title="Distribution of Time in Hospital Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=num_lab_procedures, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="# of Lab Proedures", y="Density", 
       title="Distribution of # of Lab Procedures Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=num_lab_procedures)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="# of Lab Procedures", x="Readmission Status", 
       title="Distribution of # of Lab Procedures Grouped by Readmission Status", fill="Readmission Status")
```


```{r}
ggplot(data=dat, aes(x=num_procedures, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="# of Non-Lab Proedures", y="Density", 
       title="Distribution of # of Non-Lab Procedures Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=num_procedures)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="# of Non-Lab Procedures", x="Readmission Status", 
       title="Distribution of # of Non-Lab Procedures Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=num_medications, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="# of Medications Administered", y="Density", 
       title="Distribution of # of Medications Administered Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=num_procedures)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="# of Medications Administered", x="Readmission Status", 
       title="Distribution of # Medications Administered Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=number_diagnoses, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="# of Diagnoses", y="Density", 
       title="Distribution of # of Diagnoses Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=number_diagnoses)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="# of Diagnoses", x="Readmission Status", 
       title="Distribution of # of Diagnoses Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=end_age, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="End of Age Interval", y="Density", 
       title="Distribution of End Age of Interval Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=end_age)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="End of Age Interval", x="Readmission Status", 
       title="Distribution of End Age of Interval Grouped by Readmission Status", fill="Readmission Status")
```


```{r}
ggplot(data=dat, aes(x=healthcare_utilization, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="Healtchare Utilization", y="Density", 
       title="Distribution of Healthcare Utilization by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=healthcare_utilization)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="Healthcare Utilization", x="Readmission Status", 
       title="Distribution of Healtchare Utilization Grouped by Readmission Status", fill="Readmission Status")
```


```{r}
ggplot(data=dat, aes(x=num_other_diabetes_meds_up_stdy_dwn, 
                     fill=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")))) + 
  geom_density(alpha=0.5) + 
  labs(x="# of Diabetes Medications Changed", y="Density", 
       title="Distribution of # of Diabetes Medications Changed Grouped by Readmission Status", fill="Readmission Status")
```

```{r}
ggplot(data=dat, aes(x=factor(readmitted, 
                                 labels = c("No Readmission", "Readmission in 30+ Days", "Readmission in < 30 Days")), 
                     y=num_other_diabetes_meds_up_stdy_dwn)) + 
  geom_boxplot(fill="firebrick1", alpha=0.6) + 
  labs(y="# of Diabetes Medications Changed", x="Readmission Status", 
       title="Distribution of # of Diabetes Medications Changed Grouped by Readmission Status", fill="Readmission Status")
```